### ISSUE TITLE
Apply on dynamically added images

### ISSUE THREAD

**Issue by mabrodeur** [karlhorky/gray#1]
Is there a way to call the init function other than on page load?
I have images added to page after page load and the filter doesn't work on IE10 or 11.
Thank you

**Comment by mabrodeur** [comment]
Found out how : by calling $('.grayscale').gray();
But the problem here is : if the images are absolute positioned, their positioning is gone.
Example : image at top:50px, left:50px. After calling $('.grayscale').gray(); the top and left css attributes are not transposed on the newly created div.
Also, if there is an id on the image, it is gone after init()

**Comment by karlhorky** [comment]
Good catch, thanks! I've added the feature to copy the existing element's styles to the replacement.
