### ISSUE TITLE
no fading under Firefox

### ISSUE THREAD

**Issue by jakesz** [karlhorky/gray#11]
Dear Kununu,
I have encountered an issue while implementing your grayscale script on website I work on. It seems there is no fading visible in Firefox, while on Chrome, safari opera and IE everything works fine. I would be grateful if you took a look at:
http://www.redesigned.pl/_hrp/
right column almost at the bottom gray square face thumbnails.

**Comment by jakesz** [comment]
ok, thanks!
however... now images in color return to their original size. This happens again only in Firefox. It is not desirable effect for responsive sites. Have a look here - the images are bigger:
http://www.wnetrza-adamowicz.pl/_adamowicz/

**Comment by splagemann** [comment]
The plugin doesn't support width and height attributes on the image tags. 
As a workaround for now specify width in a css class and add that to the img-tags.

**Comment by jakesz** [comment]
All right. Thanks. 
But how come it works in chrome? do you have any idea?

**Comment by splagemann** [comment]
Chrome supports css filter grayscale. Firefox does not, so we're replacing the image with a svg (and we're not checking if the image  is resized by width and height attribute on the img-tag)

**Comment by jakesz** [comment]
Hello again:) I'm a stubborn man. Yesterday a client of mine pointed out, that gray images don't work at his portfolio website in Firefox (I'm using the latest version of your script and css). Have a look: http://www.arch3dzakladarchitektury.pl/portfolio/ 
1. website is using isotope js
2. on the left there are categories. when you view all ('wszystkie') and 'przemyslowe' everything works great. However when you click any other category the grayscale filter dissapears.. 

Do you have any idea on what might be going on with that? the same happens on another website:
http://www.wnetrza-adamowicz.pl/_adamowicz/portfolio/

**Comment by karlhorky** [comment]
@jakesz which version of Firefox? Your link works in Firefox 33.0 on OSX Yosemite.

**Comment by jakesz** [comment]
FF 33.0 on mavericks and I also checked on Browserstack FF 33 + Win7. 
check this: http://www.arch3dzakladarchitektury.pl/kategorie_projektow/uzytecznosci-publicznej/
can you see color thumbs? only on this page they are gray: http://www.arch3dzakladarchitektury.pl/kategorie_projektow/przemyslowe/

**Comment by karlhorky** [comment]
[Your second link](http://www.arch3dzakladarchitektury.pl/kategorie_projektow/przemyslowe/) works for me on Firefox 33 on OSX Yosemite and Windows 7. The images start gray and then turn to color when you hover the mouse over them.

Does [the demo page](http://work.karlhorky.com/gray/) work for you in your Firefox?

**Comment by jakesz** [comment]
Yes, the demo page works well. The second link also. But any other category does not.

**Comment by karlhorky** [comment]
It looks like on your first link that jQuery is being loaded after you reference it.

![bildschirmfoto 2014-10-20 um 12 03 51](https://cloud.githubusercontent.com/assets/1935696/4699408/6e6c1244-5840-11e4-953d-d6dd29871d43.png)

**Comment by jakesz** [comment]
ok, there seems to be a problem with cookie consent plugin. I turned it off and the grayscale problem still persists.

**Comment by karlhorky** [comment]
This appears to be caused by the `display: none` on the `.item`, which is added by Isotope.

Demo: http://jsfiddle.net/bzfrn9ev/

One option is to simplify your DOM structure so that the parent is not set to `display: none`. http://jsfiddle.net/bzfrn9ev/1/

**Comment by karlhorky** [comment]
This is however a bug in the plugin. I've opened #18 to track this.

**Comment by jakesz** [comment]
All right, thank you for your help so far!

**Comment by karlhorky** [comment]
No problem, sorry that you're having problems!

**Comment by karlhorky** [comment]
@jakesz with [version 1.4.1](https://github.com/karlhorky/gray/tree/v1.4.1) you'll notice that this problem has been fixed. Thanks for reporting this.
