### ISSUE TITLE
Modernizr conflict

### ISSUE THREAD

**Issue by daveriedstra** [karlhorky/gray#13]
Plugin overrides existing Modernizr instance, could be avoided with

``` javascript
;window.Modernizr = window.Modernizr || function(a,b,c) { ... }
```

Might also be worth it to include a note in the Readme about which Modernizr features are dependencies so plugin users can create a custom build, remove the bundled instance, and lighten the overall result a bit more.

Cool plugin BTW :)

**Comment by karlhorky** [comment]
Thanks @daveriedstra, this should be fixed in 9d25d7285d2745de1cad6bc3d27ecbf3524c2c6b
