### ISSUE TITLE
Image background messes up in IE11

### ISSUE THREAD

**Issue by barrychapman** [karlhorky/gray#15]
When using this in IE11, I get the following behavior:

![image](https://cloud.githubusercontent.com/assets/152958/3950019/cedf47b2-26be-11e4-9004-eb761a3366cf.png)

![image](https://cloud.githubusercontent.com/assets/152958/3950020/d36d5dd2-26be-11e4-9fcb-aed5467e20ed.png)

![image](https://cloud.githubusercontent.com/assets/152958/3950023/d86d81cc-26be-11e4-9422-08f4a6622677.png)

These are all the same properties from the same image, along with what the image looks like. These are being applied to a List Item in an unordered list.

Any ideas?

**Comment by barrychapman** [comment]
For some reason it is appending the RGB color swatch to the url.. Not sure why?

**Comment by karlhorky** [comment]
Can you provide a demo where this fails? It seems to be appending the `background-color` (a linear gradient) to the url in the `background-image`.

**Comment by karlhorky** [comment]
@barrychapman Closing this for now. If you set up a failing demo I would be happy to open this again.
