### ISSUE TITLE
Remove Grey on Hover

### ISSUE THREAD

**Issue by TwisterMc** [karlhorky/gray#2]
I'd like to have images gray on load and once a user hovers over one they turn color. I can do that by removing the .grayscale on most browsers, but what about IE10 when we're using the inline SVG?

Do you have any sort of hover support where maybe I don't need to remove classes?

**Comment by karlhorky** [comment]
I've added a first version of the hover functionality. I'll have to check the compatibility of this but so far it works in IE10-11, Firefox, and Chrome (should work in all supported webkit browsers too).

**Comment by karlhorky** [comment]
As noted in #3, this currently causes an inconsistency in lightness in Firefox when both the normal grayscale filter and the hover filter is used in a single page.
