### ISSUE TITLE
Conflict with other JS

### ISSUE THREAD

**Issue by AgenceGrrr** [karlhorky/gray#20]
Hello,
Thank you for this code which worked very well untill I tried to use it on pages where I also need other javascript (Isotope and Flexslider). With Safari, it's OK but with Firefox and IE (10+), the images don't keep its proportions and when hovering it the background image is smaller so that it repeats itself both horizontaly and verticaly.
With Safari :
![capture d ecran 2014-10-28 a 03 06 00](https://cloud.githubusercontent.com/assets/9425365/4802591/31e43e20-5e47-11e4-8a93-1dd8e4ef3053.png)
With Firefox :
![capture d ecran 2014-10-28 a 03 04 13](https://cloud.githubusercontent.com/assets/9425365/4802598/437e50da-5e47-11e4-9fd6-d60c55e248a0.png)

I searched all day long and didn't manage to figure it out.

**Comment by karlhorky** [comment]
Did you take a look at #11 already? Can you provide an example where it fails? Does [this](https://github.com/karlhorky/gray/issues/11#issuecomment-59734984) help at all?

**Comment by karlhorky** [comment]
I'm going to close this for now. Feel free to open it if you have some more info to share.

**Comment by karlhorky** [comment]
@AgenceGrrr this also sounds a bit like #14 now that I think of it. But since then there has been a fix to allow sizing of the background images.

If you can provide a demo or a code sample I can take a look at why this is happening.
