### ISSUE TITLE
Add title to svg filter

### ISSUE THREAD

**Issue by dippas** [karlhorky/gray#26]
with this code : `'<title id="title">'+ element[0].alt  +'</title>'` in the `switchImage: function(element)`  the svg can have a title from image alt property.
With my tests It works on Firefox, But according to this http://www.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/ it can work in modern browsers

**Comment by dippas** [comment]
did you add this yet? asking this because it is been almost 2 years

**Comment by karlhorky** [comment]
I haven't gotten around to looking at any of the enhancements or bugs in the last months.

What would this take? Would you be up for opening a pull request for it?
