### ISSUE TITLE
Grayscale not showing in IE11

### ISSUE THREAD

**Issue by lakeebs** [karlhorky/gray#27]
I followed the usage and looked it over a few times but can't seem to figure it out. It works in all other browsers. I'm using v1.4.1 as seen here:

```
https://github.com/karlhorky/gray/blob/gh-pages/js/jquery.gray.min.js
```

Basically, I added "jquery.gray.min.js" in the footer after jQuery and simply initialized it like this:

```
$($el).addClass('hover grayscale grayscale-fade');
```

I know that the plugin includes some Modernizr features, and I should note that I am running a custom build of Modernizr as well on top of it. However, even removing my build of Modernizr didn't fix my issue. Is there something I overlooked?

**Comment by karlhorky** [comment]
Can you provide a reduced example where this doesn't work on IE 11? For instance on JSFiddle or similar. 

One quick thing - you should be initializing with `.gray()`, not `.addClass()`. Ex:

``` javascript
$($el).gray();
```

**Comment by lakeebs** [comment]
I'll work on the example. Regarding your note, doesn't the plugin automatically initialize for all elements with a class of `grayscale`? It works in all other browsers so I assumed that part wasn't the issue...

**Comment by karlhorky** [comment]
Yes, the plugin initializes automatically for elements with the class `grayscale`. But it doesn't watch for classes to be added later after the plugin loads the first time. So if you're adding the classes after the plugin has already loaded the first time, the plugin will not be aware of these new elements and will not add the IE10-11 polyfill to these new elements. It will still work in other browsers with CSS.

**Comment by karlhorky** [comment]
@lakeebs any update here?

**Comment by lakeebs** [comment]
Sorry, haven't had a chance to work on this for the last couple days. The (buggy) site is [here](http://staging.keebs.com). When you hover over the images, they turn gray with a low opacity. On IE, it's not there though. I'll work on this again when I get a chance to. I'm sure it's something simple I overlooked.

**Comment by karlhorky** [comment]
Okay, I'm going to close this for now. If you are still having issues, feel free to re-open.

**Comment by lakeebs** [comment]
Sorry for the late reply. I'm having a difficult time understanding how to initialize the plugin since I only want the grayscale effect to show on hover.

This is how I'm currently using the plugin: http://pastebin.com/2sKKJvYH

I tried: `$('article.project').gray();` but that didn't work. It only made the articles not show up at all in IE11. [Here is the site](http://staging.keebs.com) if you'd like to take a look at how I have everything set up.

**Comment by karlhorky** [comment]
You can accomplish an inverted hover effect (gray on hover) with CSS: https://github.com/karlhorky/gray/issues/6#issuecomment-49192788

**Comment by lakeebs** [comment]
I understand that, but I still don't understand how to actually initialize the plugin. It works on every browser but IE11.

**Comment by karlhorky** [comment]
The element will be either an image or an element with a `background-image`. In your case it works with `$('article.project img').gray()`.

**Comment by lakeebs** [comment]
That's the part I'm stuck on. If I use `$('article.project img').gray();`, it turns all of the images gray by default but my theme is coded so that the images only turn gray under specific conditions:

1) When a project hasn't been clicked and the user hovers over a project, that project turns gray.
2) While a project is loading, all other images turn gray.
3) When a project has been loaded, all other images below it remain gray.

Sorry to keep bugging you about this. I tried putting the gray.js script last in the footer but it still didn't work because, as you said, if I add the classes after the plugin has already loaded the first time, the plugin will not be aware of these new elements and will not add the IE10-11 polyfill to these new elements. This doesn't work in my case since I only want the images to turn gray under certain conditions and only when certain classes get added.

**Comment by karlhorky** [comment]
Yep, you can make it work with the CSS changes I mentioned above. Normally the grayscale effect is activated by default, but if you change the CSS, you can have it activate only when a class is added.

Then you could add and remove this class with JavaScript when you like under specific conditions.

**Comment by lakeebs** [comment]
[Live site](http://staging.keebs.com)

I'm at the point where I added `$('article.project img').gray();`, and it turned all of the images to gray by default in IE11 by adding the classes: `grayscale grayscale-replaced`. Then, in the CSS, I tried changing `.grayscale.grayscale-replaced > svg` to `opacity:0` and `.grayscale.grayscale-replaced.grayscale-off > svg, article:hover .grayscale.grayscale-replaced.grayscale-fade > svg` to `opacity:1`. Now, the images don't turn gray by default or on hover. I've since reverted the CSS back to its original form.

Full CSS file: http://pastebin.com/e24t83Nq

What part of the CSS do I have to change exactly without compromising what I already set perfectly in the other browsers? This is the part that is confusing me and I hope you can help me understand all of this.

**Comment by lakeebs** [comment]
I'm still unable to get this to work in IE11. Here is a fiddle. How can I get this to work in IE11?

http://jsfiddle.net/61jcam54/

**Comment by karlhorky** [comment]
@lakeebs did you figure this out? If not, I can provide a suggestion based on your fiddle.

**Comment by akramg478** [comment]
Hi Karlhorky Sir, I tried every thing but it did not worked at all in i.e 10, 11

Here is my URL http://e0d.9ad.myftpupload.com/

I did every thing for top banner but its not grayscale even image not shows up.

I see svg tag in the browser inspect but no image can you see it for me plzzzz :( its really killing my job now
