### ISSUE TITLE
Grayscale on hover/mouseenter

### ISSUE THREAD

**Issue by goesredy** [karlhorky/gray#39]
Can you make another class to make the grayscale class fade to gray when hover ?
So, on render, show real image, on hover show grayscale.

Thanks :)

**Comment by karlhorky** [comment]
This is possible with CSS: https://github.com/karlhorky/gray/issues/6#issuecomment-49192788

**Comment by goesredy** [comment]
Thanks :)
It could even better if you can add class to do it without replace the real css.

BTW, thanks very much for your work :+1:
