### ISSUE TITLE
Bootstrap conflict

### ISSUE THREAD

**Issue by nelsonamaya82** [karlhorky/gray#4]
Hi, first of all thank you for this awsome script.  I'm using it on a Bootstrap site and added the class "fade" to the image to achieve such effect.  However as Bootstrap has its own fade class, it just turn the image transparent (opacity 0).  How can It be fixed?

**Comment by splagemann** [comment]
Hi, yes that is a problem. As a workaround for now, you can just add the class `in` to tell bootstrap to set the opacity to `1`.

e.g.

``` html
<img src="/img/color.jpg" class="grayscale fade in">
```

**Comment by splagemann** [comment]
As bootstrap is very popular, we will change the name of that class to resolve this conflict
