### ISSUE TITLE
IE problem

### ISSUE THREAD

**Issue by strukove** [karlhorky/gray#42]
Hi there,

I had a problem in all IE browsers, svg was simply invisible. It took a lot of time to define that the problem was in visibility:hidden style on holder. I don't think it's a but I think it worth mentioning somewhere in docs.

Cheers.

**Comment by karlhorky** [comment]
Can you provide an example where this fails on JSFiddle or JS Bin?

**Comment by karlhorky** [comment]
@strukove closing this for now. Happy to re-open and look at this at this with a failing example.
