### ISSUE TITLE
Ajaxed in images not showing unless manually hovered/style altered

### ISSUE THREAD

**Issue by ghost** [karlhorky/gray#49]
I'm having an issue where images that weren't originally available on the window load event do not show up when we add the class '.grayscale'. They are in the dom, and there's no weird styles associated with them, they just simply do not appear. When I hover over them, or change any value in the console, they reappear on the screen.

I've tried to prorammatically call .gray(), and change the styles to force layout, after they are loaded in, but nothing has worked. 

Have you every come across this? I narrowed it down to the gray plugin, as removing the .grayscale class shows the images when they are loaded in.

Thanks.

**Comment by karlhorky** [comment]
I haven't encountered this issue before, no. If you could provide a bit more information, I can take a look:
- Which browser? Does it also fail in the latest Chrome, Firefox, and Edge?
- A failing demo ([jsfiddle](http://jsfiddle.net/) or something)

**Comment by karlhorky** [comment]
Closing this for now. I'll be happy to open again if you can provide some more info and a demo.
