### ISSUE TITLE
Manual calling does not seem to work.

### ISSUE THREAD

**Issue by Bitneko** [karlhorky/gray#51]
Without assign 'grayscale' class to a image, manually calling the plugin with `$('.my-class').gray()` does nothing.

**Comment by karlhorky** [comment]
Please provide a demo on JSFiddle or something where this fails.

**Comment by Bitneko** [comment]
http://jsfiddle.net/8jgy64t9/2/

I expect the line `$('.my-image').gray();` to turn the first image to grayscale but that didn't work. Adding the 'grayscale' class is the only way to grayscale the image as demonstrated in the second image.

**Comment by karlhorky** [comment]
Ah, I see what you mean. This affects browsers with support for the CSS grayscale properties. In these browsers you need to also apply the properties from [the CSS](https://github.com/karlhorky/gray/blob/gh-pages/css/gray.css) to your new class.

[Working demo](http://jsfiddle.net/8jgy64t9/3/)

I've documented this in bd181a5b527cf45e6e29c55b3c030380907fe5bb
