### ISSUE TITLE
Not seeing IE effects

### ISSUE THREAD

**Issue by jmaurer339** [karlhorky/gray#52]
Thank you for providing the plugin. I downloaded and am working to incorporate into a site. When I look at the demo at -- http://work.karlhorky.com/gray/ the effects are rendered appropriately in all browsers. But when I download and run the plugin locally, the intended effect is not rendered in IE10. Even when I simply download and extract the files open up index.html, there is no grayscale effect in IE10. Is there some other required component I might be missing? Again, thank you for providing this plugin.

**Comment by karlhorky** [comment]
It may be the root-relative jQuery urls that I used in the demo. I fixed them in d3bcbc4cb23b08a7e394cb86af04f96cf8863e3e. Please try again and confirm that it's working now.

If it still doesn't work, please provide detailed instructions to reproduce the error.

**Comment by jmaurer339** [comment]
Thank you for your reply. Upon further testing I've isolated the issue. I have been able to get the grayscale effect to render in IE10; just as it does in other browsers. What I can not do in IE10, that I can do in other browsers, is to dynamically assign class=grayscale to elements via JavaScript; specifically on onmouseover and onmouseout events. Very likely this is an issue with my JS. However, the rollover effect does render, and the class is dynamically assigned in other browsers.

The attached is a striped down example which illustrates the point. Sorry I the file suffix is in .txt and not .html. Clearly I have not correctly committed the code.
Thank You

[test_index.txt](https://github.com/karlhorky/gray/files/39560/test_index.txt)

**Comment by karlhorky** [comment]
Instead of using JavaScript you can use the CSS `:hover` pseudoclass like in [my comment in #6](https://github.com/karlhorky/gray/issues/6#issuecomment-49192788). This is also visible in the demo (**&lt;img&gt; tag with transition**).

In order to have grayscale applied on hover instead of color you just need to modify the styles as in my comment linked above.
