### ISSUE TITLE
Improve Documentation: Use Polyfill?

### ISSUE THREAD

**Issue by philnickel** [karlhorky/gray#53]
In the description stands that I must use polyfills to get Internet Explorer 10 and 11 work. I don't understand which polyfills I must use. 

Can everybody help me?

**Comment by karlhorky** [comment]
Sorry, this is unclear in the documentation. You just need to use the plugin - a polyfill is included in the plugin.

**Comment by karlhorky** [comment]
I'll keep this issue open to improve the documentation.
