### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by evovilol** [karlhorky/gray#54]
I would like to be able to install this with / via NPM, that would be awesome! :-) 

My use-case is for project that seem to use NPM for _everything_, where installing Bower would be for this one package alone.

**Comment by karlhorky** [comment]
I would like this on npm as well. I'll take a look hopefully in the next couple of days.

**Comment by karlhorky** [comment]
A simple version of the plugin is now on npm under `jquery-gray`. It's not using any module formats yet. For that I've opened #55.
