### ISSUE TITLE
Project demo not working in IE10/11.

### ISSUE THREAD

**Issue by hifall** [karlhorky/gray#56]
Out of the box, the demo on the page doesn't work in IE10/11. That is, the images supposed to be gray on page http://work.karlhorky.com/gray/ are not rendered gray. Am I missing something here?

I am using VMWare 8.0 and Microsoft's official IE VM's to test the plugin.

If you need me to collect more info, please provide instructions.

Thanks.

**Comment by karlhorky** [comment]
Try hard refreshing the page (<kbd>ctrl</kbd>-<kbd>F5</kbd>). Sometimes if you have previously visited the page the older version will be cached and will not apply the grayscale effect.

I just tried in IE 11 and 10 (IE VirtualBox VMs from Microsoft) and it is applying the effect.

**Comment by hifall** [comment]
Nope, just retried that, and it did not work.

**Comment by karlhorky** [comment]
Did you try clearing your browser data as well? Any errors in the JavaScript console? Do any of the other demos like [this one](http://jsfiddle.net/8jgy64t9/3/) work? Does it work on a physical Windows machine when you try it?

If these don't help further, maybe the following will help with troubleshooting:
- IE version
- Windows version
- IE VM version

Is there a free version of VMware that I can use to try to reproduce your environment?

**Comment by hifall** [comment]
Yes, I did clear browser cache.

I am seeing this error in the console:
SCRIPT5009: 'jQuery' is undefined
File: jquery.gray.js, Line: 6, Column: 3
This happened in IE11 in Windows 8.1, 32-bit, Build 9600, running in VMWare Fusion 8.0.

Curiously, this DOES work on a physical machine, with IE11 and Windows 8.1 installed.

**Comment by hifall** [comment]
I got the VM from: https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/.

The configuration is: Mac/IE11 on Win81/VMware.

**Comment by hifall** [comment]
I think you should be able to download a free trial of VMware from their official website.

**Comment by hifall** [comment]
Gosh, made a stupid mistake. It's not your plugin's issue.

I notice the jQuery plugin is served via Google's server, which is blocked from where I am (China). And I tested the plugin without VPN service on, and jQuery was not loaded correctly before executing your script. Now I have VPN on, and the page is looking good.

Apologize for the false alarm and your spent time.

Also, thank you for this very useful plugin.

**Comment by karlhorky** [comment]
No problem, thanks for following up on this.

I would like to use a CDN that works in China without a VPN. I have switched to MaxCDN at the advice of [this site](http://edjiang.com/post/97299595332/how-googles-cdn-prevents-your-site-from-loading). Can you confirm that [the updated demo](http://work.karlhorky.com/gray/) is working for you without VPN?

**Comment by hifall** [comment]
Yes, the updated link works!

**Comment by karlhorky** [comment]
Great, thanks. I'll close the issue?

**Comment by hifall** [comment]
Sure thing.
