### ISSUE TITLE
Fluid Layout

### ISSUE THREAD

**Issue by lisalee1004** [karlhorky/gray#58]
I have a page layout that is fluid width layout - when the window resizes the svg do don't auto resize.
I have tried adding preserveAspectRatio="xMinYMin meet" and removing the width and height in the svg definition in the js file but no luck. The svg always loads to the correct size but if I resize the browser (IE10 and 11 and razor) the svg does not auto resize.

**Comment by karlhorky** [comment]
How are you achieving the resizing on the normal image?

Can you please provide a failing demo (using a service like JSFiddle or JSBin)?

**Comment by karlhorky** [comment]
Closing this for now. I'd be happy to reopen if you provide a demo where I can play around and see exactly what is failing.
