### ISSUE TITLE
background-position center center returns an error

### ISSUE THREAD

**Issue by jeroenalewijns** [karlhorky/gray#59]
`background-position: center center;`will not work. It's compiled to `background-position: 50%;`
But at that moment you will miss the y value of the function positionToNegativeMargin where the browser returns an error. (only in IE).
The solution will be to set y = x when y is undefined.

**Comment by karlhorky** [comment]
Thanks for the bug report! Can you please provide a few things:
- failing demo

**Comment by karlhorky** [comment]
Thanks for the bug report! Can you please provide a few things:
- failing demo (using a service like JSFiddle or JSBin)
- version of failing browser
- proposed fix (using a service like JSFiddle or JSBin)

**Comment by jeroenalewijns** [comment]
failing demo http://codepen.io/JroonA/pen/Vjjaem?editors=1111 (fiddle issue #60) and change `background-position` to center center instead of 50% 50%.
Browser MS IE11

The solution will be to set y = x when y is undefined.

**Comment by karlhorky** [comment]
Non-numeric `background-position` is [currently unsupported](https://github.com/karlhorky/gray#non-numeric-background-size-and-background-position). #38 would be the issue to watch for changes to this.
