### ISSUE TITLE
background position with %

### ISSUE THREAD

**Issue by jeroenalewijns** [karlhorky/gray#60]
When you use % in your background-position the margin of the svg is not correctly set.
If I use `background-position: 50% 50%` the margin of the svg has to be 0px (better to use 0 instead of 0px) to get the correct image position.

**Comment by karlhorky** [comment]
Also here in this issue, can you please provide:
- failing demo (using a service like JSFiddle or JSBin)
- version of failing browser
- proposed fix (using a service like JSFiddle or JSBin)

**Comment by jeroenalewijns** [comment]
failing demo http://codepen.io/JroonA/pen/Vjjaem?editors=1111
Browser MS IE11
![screen shot 2016-06-15 at 14 30 20](https://cloud.githubusercontent.com/assets/2510441/16079838/bb589216-3305-11e6-828b-5f674ced76a6.png)

**Comment by karlhorky** [comment]
Just tested this and this is indeed an issue. I'll update the Readme and #38 about this.
