### ISSUE TITLE
Removed inner elements in ie browsers

### ISSUE THREAD

**Issue by dhksrini** [karlhorky/gray#61]
I have parent element with background image and 2 child element for this. I tried this plugin with css background.  It's removed child elements in IE

**Comment by karlhorky** [comment]
Hm, yes, this is not ideal. I've [documented this in the readme](https://github.com/karlhorky/gray/blob/gh-pages/README.md#child-elements-removed-in-browsers-without-support-for-css-filters).

I'll take a look at getting this fixed soon.

**Comment by karlhorky** [comment]
I've taken a shot at this and it seems complex to support all kinds of content. In addition to that, handling content is outside of the scope of the library. So this will stay a known issue. Closing this ticket.
