### ISSUE TITLE
Keep colored borders

### ISSUE THREAD

**Issue by dimbak** [karlhorky/gray#68]
Hi, i wanted to ask if there is anyway i can keep my image borders colored.

Thank you

**Comment by karlhorky** [comment]
Hi @dimbak, I'm not sure if I understand your use case completely. Do you mean CSS borders?

Right now, the polyfill will not remove color from the borders:

http://jsfiddle.net/41weta35/9/

![gray-1 4 5-ie11](https://cloud.githubusercontent.com/assets/3855671/21737416/a9a7d878-d478-11e6-9898-93c9a2f43cd7.png)

However, browsers with support for CSS filters (such as Chrome 19+ or Firefox 10+) will convert CSS border colors to grayscale. To avoid this behavior, wrap the element in a container with the borders applied.

---

If you meant borders that are part of the image itself, this is not possible - it's either the full image or nothing.

---

Does this answer your question?

**Comment by dimbak** [comment]
Yes, i am sorry for the bad description and thanks for the help, i will try your suggestion.

**Comment by karlhorky** [comment]
No problem, hope it helps! I'll close this for now, feel free to comment if we should re-open.
