### ISSUE TITLE
Bootstrap img-responsive

### ISSUE THREAD

**Issue by DrStrauss** [karlhorky/gray#69]
Hi, thank you for this great plugin ! I've been struggling so hard to get this simple task work on IE10/11.

I just have an issue with bootstrap class "img-responsive" that I was using. I've tried to add img-responsive to <svg, <image or the container <div but none of that work. I don't really understand all the styles that are applied to the container <div and I can't find the conflicting attributes.

I know you said:
Non-numeric background-size/position and percentage-based background position are not supported.

The img-responsive class adds 
display: block;
max-width: 100%;
height: auto;

No way to make this work?

**Comment by karlhorky** [comment]
Yes, currently this is unsupported. Open to considering potential solutions to this (pull requests are best!).
