### ISSUE TITLE
Images flash in color before script fires

### ISSUE THREAD

**Issue by GitFrankie** [karlhorky/gray#70]
Is there a creative way to hide the images until after the script runs? Thank you!

**Comment by karlhorky** [comment]
You could use an IE 10 and 11 hack like [these](https://gist.github.com/ricardozea/5549389#file-ie67891011-css-hacks-txt-L35-L73) with a CSS selector that will only match before the script runs (include `img` in your selector) to set them to `opacity: 0` or `visibility: hidden` or something.

Would that work?

**Comment by karlhorky** [comment]
I'm going to close this, but feel free to comment again - happy to help further if necessary!
