### ISSUE TITLE
Support of IE 10/11

### ISSUE THREAD

**Issue by JesperStender** [karlhorky/gray#75]
I installed your plugin via CDN - and added the grayscale classes - and it fixed my problem with Edge - but the images still have colours in IE 10 and 11. 
The styling is added - bit the browser tries to use filter still, and not the SVG.

Do you have any idea on how to get IE 10/11 to act like decent browsers?

**Comment by JesperStender** [comment]
Also - My images all have the same size - I see that this is a known issue - since the images is loaded via ajax. so your plugin does not know which size the SVGs should be - how can i pass the size to your plugin?

**Comment by karlhorky** [comment]
Can you provide a failing demo?

Have you taken a look at the usage examples on the [demo](https://work.karlhorky.com/gray/)?

**Comment by karlhorky** [comment]
I'm going to close this for now. Feel free to write back and I can reopen.
