### ISSUE TITLE
IE 11

### ISSUE THREAD

**Issue by mattwillms** [karlhorky/gray#76]
First. Thanks for this. I wonder if you could assist me in figuring out what is happening here in IE 11:

https://wmarble.wpengine.com

The six images in the green bar specifically: "Best new....etc..."

**Comment by karlhorky** [comment]
Did you include the jQuery plugin somewhere? I don't see it in the JavaScript...

https://github.com/karlhorky/gray#how-to-use

**Comment by mattwillms** [comment]
jQuery is there but I think there was a load order issue. Seems to be working now.

Thanks!

**Comment by karlhorky** [comment]
Great, no problem, glad to hear.
