### ISSUE TITLE
Grayscale background not working in i.e 10, 11

### ISSUE THREAD

**Issue by akramg478** [karlhorky/gray#78]
Sir I tried every thing and it adds svg image tag in browser inspect but no image shows up. It shows images gray well but backgrounds not working at all ... can you see it for me plzzzz 
Here is my URL http://e0d.9ad.myftpupload.com/

Thanks for every bit of further help plzzzz

**Comment by karlhorky** [comment]
Can you please make a simplified demo with your code? Maybe with https://jsfiddle.net/ or similar?
 There's a lot going on on that page.

**Comment by akramg478** [comment]
Sir I just need my backgrounds grayscale as you can see home page post images are working fine.

Just backgrounds took my 10 days by now :(

Sorry I can not create fiddle or any thing on it because its working fine on all browsers and also on i.e as we have graysclae images .... the only thing to figure out is why backgrounds not working ???

**Comment by karlhorky** [comment]
Maybe take a look at the examples in the demo? https://work.karlhorky.com/gray/

**Comment by karlhorky** [comment]
What is the difference between the examples and your code?

**Comment by akramg478** [comment]
No difference at all, even if you inspect my page in i.e 10, 11 it shows svg image in inside that grayscale class div but not shows that image. 

That may be due to some conflict or any thing but I tried my best to get it done buy failed ... been through all forums and stackoverflow and from your replies also etc ... but ut killing me and my job going in danger :(

**Comment by akramg478** [comment]
Even it adds that grascale-off class as well ... but the purpose is not obtained

**Comment by akramg478** [comment]
Can I use some sort of linear gradient to make my images grayscale in i.e and colored on hover ? Is it possible ?

Any code tip or any point that can make those backgrounds gray and colored on hover ?

**Comment by karlhorky** [comment]
The polyfill for IE 10 and 11 replace the original elements with an SVG element with a grayscale filter on it. IE 10 and 11 unfortunately don't support CSS filters and a gradient will not help here.

It appears that the `jquery.gray.min.js` file is being referenced in the head. As noted in [How to Use](https://github.com/karlhorky/gray#how-to-use), it should be added at the bottom of the body. This is certainly an issue and may be the problem.

In addition to that, it could be a conflict with one or more of the other scripts being loaded on the page.

**Comment by akramg478** [comment]
Thanks for your reply Sir.

I am adding jquery file in footer and its not working. Though it ads svg
image but does not show any thing. So, I removed it ans using just black
and white images.

Thanks again Sir

**Comment by karlhorky** [comment]
Okay, black and white images can also work. Should I close this issue now?

**Comment by akramg478** [comment]
Yes sure.

Really Thanks Sir for your time

**Comment by karlhorky** [comment]
No problem, I hope you find a solution that works for you.
