### ISSUE TITLE
Error when trying to import the package

### ISSUE THREAD

**Issue by dingo-d** [karlhorky/gray#80]
I'm using webpack to bundle my scripts, and when I try to load the package in the script using

```js
import gray from 'jquery-gray';
```

I get

`Uncaught TypeError: Cannot read property 'documentElement' of undefined`

It would seem like it's coming from the modernizer 🤷🏼‍♂️ 

Any idea what could be the issue?

**Comment by karlhorky** [comment]
Hm, interesting, maybe related to this (there are a few workarounds there): 

https://github.com/webpack/webpack/issues/512#issuecomment-288143187

**Comment by dingo-d** [comment]
Could be, will check it out, thnx!

**Comment by karlhorky** [comment]
@dingo-d I just published a new version `1.7.0` with the latest version of Modernizr included. Seems to be working in IE 9 and 11.

Can you upgrade and let me know whether this helps?

**Comment by dingo-d** [comment]
Yup, works perfectly when combined with the CSS `filter` on modern browsers. Thanks!

**Comment by karlhorky** [comment]
Great, thanks also for testing!
